spring:
  devtools:
    add-properties: true
  application:
    name: JsonWebToken
  datasource:
    url: jdbc:postgresql://localhost:5439/jsonwebtoken
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
jwt:
  expiryMinutes: 30
  expiryDay: 14
  accessKey: bc7eb5abc4d2495d6576fa7f139dafc884f2624e476636fb7de702757995e11b
  refreshKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfSmF2YVRlY2g=